### ISSUE TITLE
SyntaxError: Unexpected token “ when try to install with cordova

### ISSUE THREAD

**Issue by mcherubin** [wf9a5m75/phonegap-googlemaps-plugin#387]
Hello I'm trying to install the plugin for cordova with command line 
```
$ cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID='....'
```
but after getting the file I get an error: 
```
SyntaxError: Unexpected token “
    at Object.parse (native)
    at Object.get_platform_json (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/config-changes.js:461:31)
    at isPluginInstalled (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:247:42)
    at runInstall (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:271:9)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:81:16
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/cordova/node_modules/q/q.js:810:14
    at flush (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:108:17)
```
any suggestion?
Thanks

**Comment by wf9a5m75** [comment]
I have no idea. (It's not plugin's problem though)

Try to install to clean project
```
$ cordova create myproject com.example.myproject myproject
$ cd myproject
$ cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID='....'
```

**Comment by Hirbod** [comment]
The problem is your apostroph CHAR.
```“```isn't ```"``` nor ```'```

**Comment by wf9a5m75** [comment]
@mcherubin 
I think your cordova version is old, or Apache Ant is not installed is the reason of this error.
Check your environment, and use the latest version.

If you still get the same error, try to remove the cordova command, then re-install it again.
