### ISSUE TITLE
Can't build android with com.google.playservices 22.0.0 with ionic

### ISSUE THREAD

**Issue by sergiobrr** [wf9a5m75/phonegap-googlemaps-plugin#415]
Hi,
i'm trying to play with your plugin on a Nexus 5 device.
I read on another post that i should use com.google.playservices 22.0.0 to have it working properly but using that version then 
`$ionic build android `
doesn't work anymore
What i do is:
```
$ionic start myapp
$cd myapp
$ionic platform add android
$cordova plugin add https://github.com/wf9a5m75/google-play-services#v22
```

Now if i run 
`$ionic run android`
it throws an error:
`[aapt] invalid resource directory name: /home/sergio/virt/ionic/myapp/platforms/android/com.google.playservices/google-play-services_lib/bin/res crunch`

So i remove myapp/platforms/android/com.google.playservices/google-play-services_lib/bin/res
Now 
`$ionic run android`
runs fine so i install the plugin with command
`$cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="XXXXXX...."`

Now ionic run android stop working with error:
```
BUILD FAILED
/home/sergio/virt/ionic/android-sdk-linux/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/sergio/virt/ionic/android-sdk-linux/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 5 seconds

/home/sergio/virt/ionic/myapp/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/home/sergio/virt/ionic/myapp/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /home/sergio/virt/ionic/myapp/platforms/android/cordova/run: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```
And i dunno what to do to get rid of this error.
Any help appreciated
Thank you

**Comment by Hirbod** [comment]
Hi, you were close to the right way. But your not allowed to delete the "res" folder, only the crunch folder inside of it. I had the same issue once. Try to create the tea folder again, it should work.

Nonetheless, everytime you open eclipse with your project it will create this folder again.

**Comment by sergiobrr** [comment]
Hi Hirbod,
thanks for your reply.
I tried:
```
$ ionic start myapp
$ cd myapp/
$ cordova plugin add https://github.com/wf9a5m75/google-play-services#v22
$ rm -r platforms/android/com.google.playservices/google-play-services_lib/bin/res/crunch/
$ cordova plugin add plugin.google.maps --variable API_KEY_FOR_ANDROID="XXXXXX...."
$ ionic build android
```
but i get the same error:
```
BUILD FAILED
/home/sergio/virt/ionic/android-sdk-linux/tools/ant/build.xml:720: The following error occurred while executing this line:
/home/sergio/virt/ionic/android-sdk-linux/tools/ant/build.xml:734: Compile failed; see the compiler error output for details.

Total time: 9 seconds

/home/sergio/virt/ionic/myapp/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: ant with args: debug,-f,/home/sergio/virt/ionic/myapp/platforms/android/build.xml,-Dout.dir=ant-build,-Dgen.absolute.dir=ant-gen
Error: /home/sergio/virt/ionic/myapp/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/usr/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:135:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

If i just install the plugin without using the v 22 com.google.playservices it builds wihtout need to delete any folder, but then the map is blank on the device.

**Comment by wf9a5m75** [comment]
```
$> cd platforms/android/
$> ant clean
$> cd ../../
$> ionic build android
```

**Comment by wf9a5m75** [comment]
You installed `plugin.google.maps` version which is the same as master branch, however master branch uses Google Play Services v21 not v22.

In order to use v22, you have to use the test branch.
It's really different.

```
$> cordova plugin rm plugin.google.maps
$> cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID=...
```

**Comment by sergiobrr** [comment]
You' re right!!!
At the end running

```
$ ionic start myapp
$ cd myapp/
$ ionic platform add android
$ cordova plugin add https://github.com/wf9a5m75/google-play-services#v22
$ rm -r platforms/android/com.google.playservices/google-play-services_lib/bin/res/crunch/
$ cordova plugin add https://github.com/wf9a5m75/phonegap-googlemaps-plugin#test --variable API_KEY_FOR_ANDROID="...."
$ ionic run android
```
works like a charm on the device too!

Thanks a lot for quick reply!!
