### ISSUE TITLE
blank map app crash "java.lang.IllegalArgumentException: width and height must be > 0"

### ISSUE THREAD

**Issue by canadaka** [wf9a5m75/phonegap-googlemaps-plugin#586]
I have tested our app on probably 20 Android phones with no issue, but as we start to release our app, we've had 2 users inform us that the app crashes soon as they load the map and try to interact with it, or load the ionic sidemenu.

I am still trying to get more data, but I had one user submit a google crash report and send me a screenshot.

```
java.lang.IllegalArgumentException: width and height must be > 0
    at android.graphics.Bitmap.createBitmap(Bitmap.java:693)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:672)
    at android.graphics.Bitmap.createBitmap(Bitmap.java:639)
    at com.google.maps.api.android.lib6.impl.a.b$3e99e895(Unknown Source)
    at com.google.maps.api.android.lib6.impl.s$5.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:838)
```

The map is blank and no it's not API SHA key issues, as it works fine in 99% of devices.
What's also weird is the rounded tab in the middle left of the screen, never seen that before, no from our UI.
![blank map](https://cloud.githubusercontent.com/assets/108178/9142659/0e6ce0d0-3cf6-11e5-8ce4-5059732fad24.png)

**Comment by jokerxvier** [comment]
it happens to my app also. any fixed on this issue?

**Comment by canadaka** [comment]
No fixed but I've been debugging last 2 days. The user having the problem had android 4.3. I found an old phone from my wife running 4.1.2 and it has this same problem/crash. But i've tested on several 4.4 phones with no issue.

Its a major pain to get crosswalk to work with cordova android-js 3.7.2 but I managed to do it, and the above crash and weird css formatting is fixed, but the map is still blank, until you click somewhere else in the app and I briefly see the map flash. So its an improvement!

I will probably have to up the min SDK for my app to level 19 (4.4)

**Comment by Slavrix** [comment]
That tab on the left could be Samsung's quick launch bar thing possibly. So I wouldn't worry about that.

**Comment by canadaka** [comment]
This bug is still happening, we are running Crashyltics to monitor crashes. It's happened 3 times in the last several days. All 3 instances were on phones running Android > 6.0

```
Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:967)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
       at com.google.maps.api.android.lib6.impl.a.b(:com.google.android.gms.DynamiteModulesB:63)
       at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.DynamiteModulesB:1734)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by wf9a5m75** [comment]
This message means your map div is too small.

**Comment by wf9a5m75** [comment]
I guess you pass the div element that is not in the <body> element.
