### ISSUE TITLE
Build failed with android

### ISSUE THREAD

**Issue by gondor89** [wf9a5m75/phonegap-googlemaps-plugin#607]
My project build just fine without the plugins, but when I add the plugin the android build failed and here's the error message:
```
:processDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processDebugResources'.
> Error: more than one library with package name 'com.google.android.gms'
You can temporarily disable this error with android.enforceUniquePackageName=fal
se
However, this is temporary and will be enforced in 1.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 44.169 secs

C:\Users\Mohamad Ibrahim\Desktop\ShareApp\ionic-http-auth\platforms\android\cord
ova\node_modules\q\q.js:126
                    throw e;
                          ^
Error code 1 for command: cmd with args: /s /c ""C:\Users\Mohamad Ibrahim\Deskto
p\ShareApp\ionic-http-auth\platforms\android\gradlew" cdvBuildDebug -b "C:\Users
\Mohamad Ibrahim\Desktop\ShareApp\ionic-http-auth\platforms\android\build.gradle
" -Dorg.gradle.daemon=true"
ERROR building one of the platforms: Error: cmd: Command failed with exit code 8

You may not have the required environment or OS to build this project
Error: cmd: Command failed with exit code 8
    at ChildProcess.whenDone (C:\Users\Mohamad Ibrahim\AppData\Roaming\npm\node_
modules\cordova\node_modules\cordova-lib\src\cordova\superspawn.js:139:23)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Process.ChildProcess._handle.onexit (child_process.js:802:5)
```
I'd appreciate any help.

**Comment by Hirbod** [comment]
Update Cordova

**Comment by gondor89** [comment]
My cordova version is 5.2.0 I think it's the latest right?

**Comment by Hirbod** [comment]
Update android cordova to 4.+, update config.xml, set minSdkVersion to 14 (better 16) and check your SDK-Manager. You need to install "Google Repository"

<img width="1335" alt="bildschirmfoto 2015-09-14 um 10 28 55" src="https://cloud.githubusercontent.com/assets/504909/9845520/cb08e278-5acb-11e5-9cd6-cc4d98abb2cc.png">
