### ISSUE TITLE
Update plugin by using monaca

### ISSUE THREAD

**Issue by Tong2203** [wf9a5m75/phonegap-googlemaps-plugin#608]
Hi, I want to update plugin by using monaca.
But I can't build success.

error message:
```
Temporary folder: /private/tmp/monaca/55efbf0d7e2193f6144ff7d8
Downloading project
Download complete
Running for 3.5
Installing &quot;android.support.v4&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Installing &quot;com.google.playservices&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Updated local.properties
No project name specified, using project folder name &apos;google-play-services_lib&apos;.
If you wish to change it, edit the first line of build.xml.
Added file /private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/com.google.playservices/google-play-services_lib/build.xml
Added file /private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/com.google.playservices/google-play-services_lib/proguard-project.txt
PLUGIN IS DEPRECATED: com.google.playservices

Plugins should use framework tags instead.

E.g.:
    &lt;framework src=&quot;com.google.android.gms:play-services-plus:+&quot; /&gt;
    &lt;framework src=&quot;com.google.android.gms:play-services-identity:+&quot; /&gt;&gt;

Full list available: http://developer.android.com/google/play-services/setup.html
  
Installing &quot;com.googlemaps.ios&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Installing &quot;com.wikitude.phonegap.WikitudePlugin&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Installing &quot;mobi.monaca.plugins.Monaca&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Installing &quot;mobi.monaca.plugins.WebIntent&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Installing &quot;org.apache.cordova.device&quot; for android
Installing &quot;org.apache.cordova.dialogs&quot; for android
Installing &quot;org.apache.cordova.file&quot; for android
Installing &quot;org.apache.cordova.file-transfer&quot; for android
Installing &quot;org.apache.cordova.geolocation&quot; for android
Installing &quot;org.apache.cordova.globalization&quot; for android
Installing &quot;org.apache.cordova.ibeacon&quot; for android
Installing &quot;org.apache.cordova.inappbrowser&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Installing &quot;org.apache.cordova.media&quot; for android
Installing &quot;org.apache.cordova.network-information&quot; for android
Installing &quot;org.apache.cordova.splashscreen&quot; for android
Installing &quot;org.apache.cordova.vibration&quot; for android
Installing &quot;plugin.google.maps&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Installing &quot;plugin.http.request&quot; for android
cordova version not detected (lacks script &quot;/private/tmp/monaca/55efbf0d7e2193f6144ff7d8/android/skeleton/platforms/android/cordova/version&quot; ), continuing.
Error during processing of action! Attempting to revert...
Failed to install &apos;plugin.google.maps&apos;:Error: Uh oh!
cannot find &quot;/Applications/adt-bundle-mac/sdk/com.google.android.gms:play-services-maps:+/project.properties&quot; referenced in &lt;framework&gt;
    at Object.AndroidProject.addSubProject (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/android-project.js:69:51)
    at module.exports.framework.install (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:110:27)
    at Object.ActionStack.process (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:70:25)
    at handleInstall (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:560:20)
    at /data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:320:20
    at _fulfilled (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:760:13)
    at /data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:574:44
    at flush (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:108:17)
Error: Uh oh!
cannot find &quot;/Applications/adt-bundle-mac/sdk/com.google.android.gms:play-services-maps:+/project.properties&quot; referenced in &lt;framework&gt;
    at Object.AndroidProject.addSubProject (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/android-project.js:69:51)
    at module.exports.framework.install (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:110:27)
    at Object.ActionStack.process (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:70:25)
    at handleInstall (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:560:20)
    at /data/monaca_build_module/3.5/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:320:20
    at _fulfilled (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:798:54)
    at self.promiseDispatch.done (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:827:30)
    at Promise.promise.promiseDispatch (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:760:13)
    at /data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:574:44
    at flush (/data/monaca_build_module/3.5/node_modules/cordova/node_modules/q/q.js:108:17)
Build error: Error building project source code

```

could you update the "Tutorial for Monaca" ?
think you very much

**Comment by Hirbod** [comment]
Sorry, but feel free to submit an update, I have no experience with monaca.

**Comment by Hirbod** [comment]
Set your correct SDK Path and check inside of ANDROID SDK Manager that you have included "Google Repostories"
