### ISSUE TITLE
Compiling Android in Mac

### ISSUE THREAD

**Issue by snowbreeze** [wf9a5m75/phonegap-googlemaps-plugin#668]
A problem occurred configuring root project 'android'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find any version that matches com.google.android.gms:play-services-maps:+.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/maven-metadata.xml
         https://repo1.maven.org/maven2/com/google/android/gms/play-services-maps/

BUILD FAILED

Total time: 8.356 secs

/Applications/MAMP/htdocs/MapTest/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                    ^
Error code 1 for command: /Applications/MAMP/htdocs/MapTest/platforms/android/gradlew with args: cdvBuildDebug,-b,/Applications/MAMP/htdocs/MapTest/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /Applications/MAMP/htdocs/MapTest/platforms/android/cordova/build: Command failed with exit code 1
You may not have the required environment or OS to build this project
Error: /Applications/MAMP/htdocs/MapTest/platforms/android/cordova/build: Command failed with exit code 1
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

My envos

ANDROID_HOME=/usr/local/Cellar/android-sdk/24.2
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home

**Comment by snowbreeze** [comment]
Solved by installing Support Libraries
